#!/bin/bash
# another example of how not to use the for command
for test in I don\'t know if “this'll” work
do
echo “word:$test”
done
$ ./test2
word:I
word:don't
word:know
word:if
word:this'll
word:work
